import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import Header from '../components/Footer'
import Footer from '../components/Header'
import RecoilRootWrapper from '@/components/RecoilRootWrapper'
import './globals.css'

const inter = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootWrapper>
          <Header />
          {children}
          <Footer/>
        </RecoilRootWrapper>
      </body>
    </html>
  )
}
