import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Providers from '@/components/Providers'
import './globals.css'

const inter = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
